# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    image: ghcr.io/arqpdatateam/log_template_app:latest
    container_name: log_template_app
    restart: always
    ports:
      - "80:8080"